---
- name: Install Nginx
  apt:
    package: nginx

- name: Generate OpenBounty Nginx proxy
  template:
    src: nginx_proxy.conf.j2
    dest: '/etc/nginx/sites-enabled/openbounty_proxy.conf'
    mode: 0644
  notify:
    - Restart nginx

