---
sob_branch: 'deploy-prod'
sob_db_name: 'commiteth'
sob_db_user: '{{lookup("passwordstore", "services/openbounty/prod/db-user")}}'
sob_db_pass: '{{lookup("passwordstore", "services/openbounty/prod/db-pass")}}'
# if anable dummy data will be loaded into the database
sob_testing: false
sob_domain: openbounty.status.im

# necessary to connect to the database
sob_jdbc_url: 'jdbc:postgresql://database:{{ db_cont_port }}/{{ sob_db_name }}?user={{ sob_db_user }}&password={{ sob_db_pass }}'

sob_settings:
  # Secrets
  github-user:           '{{lookup("passwordstore", "services/openbounty/github-user")}}'
  github-password:       '{{lookup("passwordstore", "services/openbounty/github-pass")}}'
  github-client-id:      '{{lookup("passwordstore", "services/openbounty/prod/github-client-id")}}'
  github-client-secret:  '{{lookup("passwordstore", "services/openbounty/prod/github-client-secret")}}'
  eth-account:           '{{lookup("passwordstore", "services/openbounty/prod/eth-account")}}'
  eth-password:          '{{lookup("passwordstore", "services/openbounty/prod/eth-password")}}'
  webhook-secret:        '{{lookup("passwordstore", "services/openbounty/prod/webhook-secret")}}'
  hubspot-api-key:       '{{lookup("passwordstore", "services/openbounty/prod/hubspot-api-key")}}'
  hubspot-contact-create-enabled: true
  # paths
  eth-wallet-file:       '/root/ethereum-wallet'
  html2png-command:      '/root/html2png.sh'
  # ethereum
  on-testnet:            false
  gas-price:             15000000000
  gas-estimate-factor:   1.1
  auto-gas-price:        true
  contract-factory-addr: '0x3B9A3c062Bdb640b5039C0cCda4157737d732F95'
  tokenreg-addr:         '0x5f0281910af44bfb5fc7e86a404d0304b0e042f1'
  eth-rpc-url:           'https://mainnet.infura.io/wWcrPlB1kLlxod3qy7Pz'
  tokenreg-base-format:  ':parity'
  # general
  port:                  3000
  nrepl-port:            7000
  session-timeout:       180
  server-address:        'https://{{ sob_domain }}'
  # database
  jdbc-database-url:     '{{ sob_jdbc_url }}'

sob_testnet_token_data:
  - ':D0X { :tla "D0X", :base 1000000000000000000, :address "0x0abdace70d3790235af448c88547603b945604ea", :owner "0x0053602cf6cb33f41bf2324523eb2f1e958d07b4", :name "district0x Network Token" }'
  - ':SWT { :tla "SWT", :base 1000000000000000000, :address "0xb9e7f8568e08d5659f5d29c4997173d84cdf2607", :owner "0x13370ca2e8426a82bcfcce21c97817a243c521cf", :name "Swarm City Token" }'
  - ':MYB { :tla "MYB", :base 1000000000000000000, :address "0x5d60d8d7ef6d37e16ebabc324de3be57f135e0bc", :owner "0x0097971b7f70ae0ba3dce0cec00379309be24ef3", :name "MyBit" }'
  - ':SNT { :tla "SNT", :base 1000000000000000000, :address "0x744d70fdbe2ba4cf95131626614a1763df805b9e", :owner "0x6f680fcfc0cb98072ad066e207af814fdde4fe8f", :name "Status Network Token" }'
  - ':ANT { :tla "ANT", :base 1000000000000000000, :address "0x960b236a07cf122663c4303350609a66a7b288c0", :owner "0x6f680fcfc0cb98072ad066e207af814fdde4fe8f", :name "Aragon Network Token" }'

sob_token_blacklist:
  - PNS
  - PRO

sob_users_whitelist:
  - Araq
  - Chu127001
  - GriffGreen
  - JoAz111
  - Smokyish
  - Torpir
  - alegw
  - alexvandesande
  - andytudhope
  - anmonteiro
  - anna09test
  - ara4n  
  - arichiardi
  - balance-io
  - bobjiang
  - carlbennetts
  - churik
  - cjdowner
  - dob
  - ericxtang
  - etiennetatur
  - faffydee
  - flexsurfer
  - geleeroyale
  - holiman
  - iurimatias
  - izqui
  - jacqueswww
  - jarradh
  - jeluard
  - jiangbubai
  - jjperezaguinaga
  - jmpolitzer
  - jpitts
  - kikipluche
  - lampholder
  - leonprou
  - nohaapav
  - pablanopete
  - perissology
  - quazia
  - ricburton
  - rolandkofler
  - satyavh
  - shyblugs
  - syoyo
  - tpatja
  - trowacat
  - vojtechsimetka
  - yalormewn
  - zah
